FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*
    RUN apt-get update && \
    apt-get install -y \
      curl \
      bash

WORKDIR /app
COPY ./scripts/requirements.txt .

RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install git-all -y
RUN apt-get install -y gcc-12 g++-12 libnuma-dev

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12
RUN git clone --branch v0.8.5 https://github.com/vllm-project/vllm.git vllm_source

RUN pip3 install cmake>=3.26 wheel packaging ninja setuptools-scm>=8 numpy --break-system-packages
RUN cd vllm_source && pip3 install -v -r requirements/cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu --break-system-packages
RUN cd vllm_source && VLLM_TARGET_DEVICE=cpu python3 setup.py install

RUN pip3 install fastapi --break-system-packages
RUN pip3 install qwen_vl_utils --break-system-packages
RUN pip3 install accelerate --break-system-packages
RUN pip3 install timm --break-system-packages
RUN pip3 install codecarbon --break-system-packages
RUN pip3 install transformers==4.51.0 --break-system-packages
COPY ./scripts .

EXPOSE 8000
# Définir la commande de démarrage
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]