services:
  ollama:
    restart: always
    volumes:
      - ../../volumes/ollama:/root/.ollama
    build:
      context: .
      dockerfile: Dockerfile
    image: openrag_ollama
    container_name: ${ollama_LOCAL_CONTAINER_NAME}
    pull_policy: always
    tty: true
    environment:
      OLLAMA_MAX_LOADED_MODELS: 5
      OLLAMA_NUM_PARALLEL: 10
      OLLAMA_ORIGINS: "*"
      OLLAMA_KEEP_ALIVE: "60m"
    ports:
        - 11434:11434
